version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aqa_hillel_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: aqa_hillel_docker_test_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test_network
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    networks:
      - test_network
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db:5432", "--", "pytest", "test_my_aqa_docker_db.py"]

networks:
  test_network:
    driver: bridge