css_locator_1: str = "a.header_logo"
css_locator_2: str = ".btn.header-link.-active"
css_locator_3: str = "button[appscrollto='aboutSection']"
css_locator_4: str = "button[appscrollto='contactsSection']"
css_locator_5: str = "div[class = 'header_right d-flex align-items-center']"
css_locator_6: str = "button[class = 'header-link -guest']"
css_locator_7: str = "button[class = 'btn btn-outline-white header_signin']"
css_locator_8: str = "button[class = 'hero-descriptor_btn btn btn-primary']"
css_locator_9: str = "div[class='col-12 col-lg-6'] img[alt='Instructions']"
css_locator_10: str = "div[class='col-12 col-lg-6 mt-lg-0 mt-md-5 mt-sm-4 mt-3'] img[alt='Instructions']"
css_locator_11: str = "div[class='col-md-6 d-flex flex-column align-items-center align-items-md-start'] h2"
css_locator_12: str = "span[class$='facebook']"
css_locator_13: str = "span[class$='telegram']"
css_locator_14: str = ".socials_icon.icon.icon-youtube"
css_locator_15: str = ".socials_icon.icon.icon-instagram"
css_locator_16: str = ".socials_icon.icon.icon-linkedin"
css_locator_17: str = "*[class^='hero']"
css_locator_18: str = "div[class = 'section about']"
css_locator_19: str = "div[class = 'section contacts']"
css_locator_20: str = "div>button[class = 'btn btn-outline-white header_signin']"