XPath_selector_1: str = ".//a[@class='header_logo']//*[name()='svg']"
XPath_selector_2: str = ".//nav[contains(@class, 'header_nav')]//a[contains(@class, 'btn')]"
XPath_selector_3: str = ".//button[text()='About']"
XPath_selector_4: str = ".//button[text()='Contacts']"
XPath_selector_5: str = ".//div[contains(@class,'header_right') or contains(class,'d-flex')]//button"
XPath_selector_6: str = ".//div//button[text() = 'Guest log in']"
XPath_selector_7: str = ".//div//button[contains(@class, 'btn btn-outline-white header_signin')]"
XPath_selector_8: str = ".//div//button[text() = 'Sign up']"
XPath_selector_9: str = ".//div[@id = 'movie_player']"
XPath_selector_10: str = ".//img[@alt = 'Instructions']"
XPath_selector_11: str = ".//img[@alt = 'Instructions' and contains(@src,'info_1.jpg')]"
XPath_selector_12: str = ".//img[@alt = 'Instructions' and contains(@src,'info_2.jpg')]"
XPath_selector_13: str = ".//h2[text() = 'Contacts']"
XPath_selector_14: str = ".//div[@class='contacts_socials socials' and contains(@xpath,'1')]//a"
XPath_selector_15: str = ".//div//a[contains(@href,'facebook.com')]//span[contains(@class, 'facebook')]"
XPath_selector_16: str = "..//div//a[contains(@href,'t.me')]//span[contains(@class, 'telegram')]"
XPath_selector_17: str = ".//div//a[contains(@href,'youtube.com')]//span[contains(@class, 'youtube')]"
XPath_selector_18: str = ".//div//a[contains(@href,'instagram.com')]//span[contains(@class, 'instagram')]"
XPath_selector_19: str = ".//div//a[contains(@href,'linkedin.com')]//span[contains(@class, 'linkedin')]"
XPath_selector_20: str = ".//div//a[contains(@href,'ithillel.ua') and contains(text(),'ithillel.ua')]"
XPath_selector_21: str = ".//div//a[contains(@href,'https://ithillel.ua') and contains(text(),'ithillel.ua')]"
XPath_selector_22: str = ".//div//a[contains(@href,'developer@ithillel.ua') and contains(text(),'ithillel.ua')]"
XPath_selector_23: str = ".//div//a[contains(@aria-label,'Смотреть это видео') and contains(@href,'youtube')]"
XPath_selector_24: str = "//button[@title='Смотреть']"
XPath_selector_25: str = ".//div[@class = 'ytp-share-title' and text() = 'Поделиться']"